scripts:
  - &get_flutter_packages
    name: Get Flutter packages
    working_directory: mobile
    script: |
      flutter packages pub get

definitions:
  workflow_trigger: &workflow_trigger
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
        - pattern: master
        - pattern: develop
    when:
      changeset:
        includes:
          - "mobile/"

  env_versions: &env_versions
    flutter: stable
    xcode: latest
    cocoapods: default

  cache: &cache
    cache_paths:
      - $FLUTTER_ROOT/.pub-cache
      - $HOME/.gradle/caches
      - $HOME/Library/Caches/CocoaPods

  publishing_email: &publishing_email
    email:
      recipients:
        - support@gallery-found.jp
      notify:
        success: false
        failure: true

workflows:
  android-workflow:
    name: Android Workflow
    <<: *workflow_trigger
    instance_type: mac_mini_m1
    max_build_duration: 20
    environment:
      <<: *env_versions
      android_signing:
        - keystore_reference
      groups:
        - google_credentials
      vars:
        GOOGLE_PLAY_TRACK: internal
    cache:
      <<: *cache
    scripts:
      - name: Set up local.properties
        working_directory: mobile
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/mobile/android/local.properties"
      - *get_flutter_packages
      - name: Build AAB with Flutter
        working_directory: mobile
        script: |
          flutter build appbundle --release \
            --build-number=$PROJECT_BUILD_NUMBER \
    artifacts:
      - mobile/build/**/outputs/**/*.aab
      - mobile/build/**/outputs/**/mapping.txt
      - mobile/flutter_drive.log
    publishing:
      <<: *publishing_email
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true

  ios-workflow:
    name: iOS Workflow
    <<: *workflow_trigger
    instance_type: mac_mini_m1
    max_build_duration: 20
    integrations:
      app_store_connect: GalleryFound Codemagic

    environment:
      <<: *env_versions
      ios_signing:
        certificates:
          - galleryfound_certificate
        provisioning_profiles:
          - galleryfound_profile
      groups:
        - appstore_credentials
        - git_credentials

    cache:
      <<: *cache

    scripts:
      # 署名設定
      - name: Set up code signing settings on Xcode project
        working_directory: mobile/ios
        script: |
          xcode-project use-profiles

      # 依存取得
      - *get_flutter_packages

      # Pods インストール（失敗時に clean → repo update → 再インストール）
      - name: Install pods (auto clean & repo update when needed)
        working_directory: mobile/ios
        script: |
          set -e

          echo "▶︎ 1st try: pod install"
          if pod install; then
            echo "✅ Pods installed successfully on first try."
          else
            echo "⚠️  Pod install failed. Cleaning & updating specs ..."

            # flutter clean (プロジェクトルートで)
            pushd ..
            flutter clean
            flutter pub get
            popd

            # Pods／Podfile.lock を削除して再構築
            rm -rf Pods Podfile.lock

            # CocoaPods specs 更新
            pod repo update

            echo "▶︎ 2nd try: pod install after clean & repo update"
            pod install

            # repo update が走った証明ファイルを残す
            touch /tmp/pod_repo_updated
          fi

      # Podfile/Podfile.lock の変更を Push & PR
      - name: Commit & PR if Podfile changed
        working_directory: mobile
        script: |
          set -e

          # Git ユーザー設定
          git config --global user.name  "Codemagic Bot"
          git config --global user.email "codemagic-bot@gallery-found.jp"

          # 変更の有無を確認
          if git diff --quiet --exit-code -- ios/Podfile ios/Podfile.lock; then
            echo "🟢 No changes in Podfile / Podfile.lock. Skipping PR."
            exit 0
          fi

          # PAT を使った HTTPS URL に差し替え
          git remote set-url origin "https://x-access-token:${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/FltSv/GalleryFound.git"

          # ブランチ名をユニークに生成
          BRANCH="cm/cocoapods-update-$(date +%Y%m%d-%H%M%S)"

          git checkout -b "$BRANCH"
          git add ios/Podfile ios/Podfile.lock
          git commit -m "chore(ios): Update CocoaPods dependencies via CI"
          git push origin "$BRANCH"

          # gh CLI は macOS runner にプリインストール。無い場合だけ brew で入れる
          if ! command -v gh >/dev/null 2>&1; then
            brew install gh
          fi

          export GH_TOKEN="$GITHUB_PERSONAL_ACCESS_TOKEN"

          # 既に同名 PR が無いか確認してから PR 作成
          if gh pr list --head "$BRANCH" --json url -q '.[].url' | grep -q .; then
            echo "🔄 Pull Request already exists."
          else
            gh pr create \
              --title "Update CocoaPods deps ($BRANCH)" \
              --body  "Automated Pods update generated by Codemagic CI 🚀" \
              --base  "$CM_BRANCH" \
              --head  "$BRANCH"
          fi

      # IPA ビルド
      - name: Flutter build ipa
        working_directory: mobile
        script: |
          flutter build ipa --release \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - mobile/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - mobile/flutter_drive.log
    publishing:
      <<: *publishing_email
      app_store_connect:
        auth: integration
        submit_to_testflight: true
