# masterブランチへのマージ時に公開サイトへのデプロイを行います。

name: Deploy Production
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Hosting
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
        env:
          VITE_MAPS_JS_API: ${{ secrets.MAPS_JS_API }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GALLERY_FOUND }}
          entryPoint: ./Hosting
          channelId: live
          projectId: gallery-found
