# mainブランチへのマージ時に、指定のチャンネルへのデプロイを行います。

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    environment: production
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Hosting
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
        env:
          MAPS_JS_API: ${{ secrets.MAPS_JS_API }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GALLERY_FOUND }}
          entryPoint: ./Hosting
          expires: 30d
          channelId: alpha
          projectId: gallery-found
