name: Flutter Lint
on:
  pull_request:
    paths:
      - "mobile/**"

defaults:
  run:
    working-directory: mobile

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache flutter dependencies
        uses: actions/cache@v3
        with:
          # Flutter の pub パッケージキャッシュ
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('mobile/pubspec.yaml', 'mobile/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - run: flutter pub get

      - name: Run Flutter Analyzer and Convert Output
        run: |
          # || true で処理継続
          flutter analyze --machine | flutter pub global run analyzer_to_checkstyle > checkstyle.xml || true

      - name: Run reviewdog
        uses: reviewdog/action-setup@v1
        with:
          name: flutter
          reporter: github-pr-review
          fail_on_error: true
          tool_name: flutter_analyzer
          format: checkstyle
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
